num_rollouts: 4096 # 前向采样次数
dyn_block_size: 32 # 动力学模型块大小
horizon: 60 # 单位：步
dt: 0.05 # 单位：秒
x_weight : [100, 100, 10, 0.1, 0.1, 0.1] # 状态变量权重
lambda : 1.0 # 正则化/学习率参数
alpha : 0.0 # 探索参数
iter: 1 # 滚动优化迭代次数
heartbeat_duration: 0.1 # 控制器心跳周期
topics:
  observation: /wamv/sensors/position/p3d_wamv
  target: /wamv/target_position
  left_thrust: /wamv/thrusters/left_thrust_cmd
  right_thrust: /wamv/thrusters/right_thrust_cmd


