num_rollouts: 4096 # 前向采样次数
dyn_block_size: 32 # 动力学模型块大小
horizon: 100 # 单位：步
dt: 0.1 # 单位：秒
x_weight : [100, 100, 10, 0.1, 0.1, 0.1] # 状态变量权重
lambda : 1.0 # 正则化/学习率参数
alpha : 0.0 # 探索参数
iter: 1 # 滚动优化迭代次数



