num_rollouts: 4096 # 前向采样次数
dyn_block_size: 32 # 动力学模型块大小
horizon: 100 # 单位：步
dt: 0.05 # 单位：秒
x_weight : [100, 100, 1, 0.1, 0.1, 0.1] # 状态变量权重
lambda : 1.0 # 正则化/学习率参数
alpha : 0.0 # 探索参数
iter: 4 # 滚动优化迭代次数
heartbeat_duration: 0.1 # 控制器心跳周期
stddev: 200 # 控制器噪声标准差
exponents: 0.5 # 有色噪声相关性参数
dynamics_test: # 以实际动力学为准[-.5,.5]
  left_input: 100 # 左推力输入
  right_input: 0 # 右推力输入
topics:
  observation: /wamv/sensors/position/p3d_wamv
  target: /wamv/target_position
  left_thrust: /wamv/thrusters/left_thrust_cmd
  right_thrust: /wamv/thrusters/right_thrust_cmd
simulation:
  time_total: 500.0 # 单位：秒
  traj_type: circle # 轨迹类型
  radius: 20.0 # 圆形轨迹半径
  omega: 0.1 # 圆形轨迹角速度
  amplitude_x: 3.4 # 轨迹x方向振幅
  amplitude_y: 4.8 # 轨迹y方向振幅
  angular_x: 0.5 # 轨迹x方向角速度
  angular_y: 0.25 # 轨迹y方向角速度
  x_goal: 10.0 # 目标x坐标
  y_goal: 10.0 # 目标y坐标
  psi_goal: 0.0 # 目标航向角

